#!/usr/bin/env python
# -*- coding: utf-8 -*-

# PlotDist

import sys
from numpy import histogram,percentile

# TODO make these passable options
BINS=60
HEIGHT=10
CHARS={'full_top':'┃', 'half_top':'╻', 'fill':'┃'}

def draw_hist(normed_hist_list,shape):
    """ takes a list of histogram bin counts and shape(min,max) of input """
    
    # TODO make the offset configurable
    y_offset = '       '
    y_label  = ' prop. '

    print ""
    # Build plot from top level
    for depth in range(HEIGHT-1,-1,-1):

        # Draw Y axis
        if depth == HEIGHT/2:
            sys.stdout.write(y_label+'│')
        else:
            sys.stdout.write(y_offset+'│')

        # Draw bars
        for item in normed_hist_list:
            if floor(item) >= depth:
                if floor(item) == depth and item % 1 < 0.75 and item%1 >0.25:
                    sys.stdout.write( CHARS['half_top'] )
                elif floor(item) == depth and item % 1 > 0.75 :
                    sys.stdout.write( CHARS['full_top'] )
                elif floor(item) > depth:
                    sys.stdout.write( CHARS['fill'] )
                else:
                    sys.stdout.write(' ')
                continue
            else:
                sys.stdout.write(' ')
        print ""

    # Draw X axis 
    print y_offset + '└'+ "─"*(BINS+2)
    print y_offset + str(shape[0]) + ' '*(BINS-3) + str(shape[1])

def floor(val):
    """ only because I don't want to use math.floor """
    int_part = int(str(val).split('.')[0])
    return int_part

def main():
    input_data = sys.stdin.read().strip('\n')
    input_list = input_data.split('\n')
    
    # Convert input to floats
    try:
        input_list = map(float,input_list)
    except:
        raise SystemError("Failed to convert input to float")
    

    hist_list,bin_edges = histogram(input_list,bins=BINS)
    max_count = max(hist_list)
    shape = ( min(input_list), max(input_list) )
    normed_hist_list = [ float(x)*HEIGHT/max_count for x in hist_list ]
    
    # Draw the histogram
    draw_hist(normed_hist_list,shape)
 
    # Calculate stats on data
    print '\ncount      :',len(input_list)
    for perc in [25,50,75]:
        print "{0}th perc. :".format(perc), percentile(input_list,perc)
    

if __name__ == '__main__':
    main()
